mongodb-connectionstring: "mongodb://root:password@host:27017"
discordtoken: "TOKEN_HERE"
webhook: "WEBHOOK_HERE"
chatchannel: "ID_HERE"
afktime: 15
joined-so-far: 0
modules:
  chatsystem:
    enabled: true
    # supports placeholder API
    format: "%nations_rank%&f%nations_nation% &8| %vault_prefix%%player_displayname% &8» &7%message%"
    # set to 0.0 if you want it to be disabled
    cooldown: 1.0
    blacklist: ["badword1", "nonoword2"]
    muted: false
  privatemessage:
    enabled: true
    # supports placeholder API
    format-receiver-player: "%vault_prefix%%player_displayname% §8» §3§lYOU §8| §7%message%"
    format-receiver-console: "§cCONSOLE §8» §3§lYOU §8| §7%message%"
    format-sender: "§3§lYOU §8» %vault_prefix%%player_displayname% §8| §7%message%"
  warps:
    enabled: true
  economy:
    enabled: true
    min-amount: 1.0
  shopsystem:
    enabled: true
  homesystem:
    helper: 3
    mod: 3
    admin: 666
    dev: 666
    manager: 666
    ultimate: 5
    snow: 4
    nitrogen: 4
    royal: 3
    corporal: 3
    default: 1
