name: PixliesEarthCore
version: 1.0
main: eu.pixliesearth.Main
api-version: 1.13
depend:
  - Vault
softdepend:
  - PlaceholderAPI
authors: [MickMMars, Machmeinparaillegal]
description: PixliesEarth core
commands:
  modules:
    description: Modules command
  chat:
    description: Chat Command
  seen:
    description: Seen Command
    aliases:
      - lastseen
  coins:
    description: Main command for pixliecoins
    aliases:
      - pixliecoins
  message:
    description: PM command
    aliases:
      - msg
      - pm
      - privatemessage
      - dm
      - tell
  profile:
    description: profile to string
    aliases:
      - settings
  link:
    description: Discord link command
  nation:
    description: nation command
    aliases:
      - n
      - nations
  warp:
    description: warps
    aliases:
      - warps
  backup:
    description: backup
  economy:
    description: Economy command
    aliases:
      - eco
      - money
  balance:
    description: bal
    aliases:
      - bal
  heal:
    description: heal
    aliases:
      - hl
  feed:
    description: feed
    aliases:
      - fd
  gmc:
    description: gmc
    aliases:
      - gm1
  gms:
    description: gms
    aliases:
      - gm0
  gmsp:
    description: gmsp
    aliases:
      - gm2
  gma:
    description: gma
    aliases:
      - gm3
  staff:
    description: staff
    aliases:
      - admin
      - override
  flyspeed:
    description: flyspeed
    aliases:
      - fs
  fly:
    description: fly
  suicide:
    description: suicide
    aliases:
      - kms
  pay:
    description: pay
  broadcast:
    description: broadcast
    aliases:
      - bc
      - announce
  vanish:
    description: vanish
    aliases:
      - v
  tpa:
    description: tpa
    aliases:
      - tprq
      - tpr
  tpaccept:
    description: tpaccept
    aliases:
      - tpaaccept
  enderchest:
    description: Enderchest
    aliases:
      - ec
      - echest
  craft:
    description: craft
    aliases:
      - crafter
      - workbench
  skull:
    description: skull
  walkspeed:
    description: walkspeed
  gungive:
    description: gungive
    aliases:
      - givegun
  shop:
    description: shopsystem
  lobby:
    description: send to lobby
    aliases:
      - hub
  boost:
    description: boosts
    aliases:
      - boosts
      - serverboost
  cigive:
    description: cigive
    aliases:
      - giveci
  marry:
    description: marriage command
    aliases:
      - propose
  divorce:
    description: divorce command
    aliases:
      - breakup
  sudo:
    description: sudo command
  tphere:
    description: tphere command
  family:
    description: show family info
  sex:
    description: Have sex
  adopt:
    description: Adopt command
  block:
    description: Block player
    aliases:
      - ignore
  nick:
    description: nick
    aliases:
      - nickname
      - disguise
  realname:
    description: realname

permissions:
  # GENERAL
  earth.admin:
    default: op
  earth.seen:
    default: op
  earth.heal:
    default: op
  earth.feed:
    default: op
  earth.flyspeed:
    default: op
  earth.fly:
    default: op
  earth.vanish:
    default: op
  earth.seevanished:
    default: op
  earth.craft:
    default: op
  earth.enderchest:
    default: op
  earth.skull:
    default: op
  earth.walkspeed:
    default: op
  earth.sudo:
    default: op
  earth.tphere:
    default: op
  earth.nick:
    default: op
  earth.nick.colours:
    default: op
  earth.nick.others:
    default: op
  earth.realname:
    default: op
  earth.chat.hex:
    default: op
  earth.bypass.fullkick:
    default: op
  earth.bypass.whitelist:
    default: op

  # CHAT
  earth.chat.colours:
    default: op
  earth.chat.bypasscooldown:
    default: op
  earth.chat.bypassmute:
    default: op
  earth.chat.bypassblacklist:
    default: op
  earth.chat.broadcast:
    default: op
  # COINS
  earth.coins.admin:
    default: op
  earth.coins.others:
    default: op
  # PRIVATEMESSAGE
  earth.pm.bypassblacklist:
    default: op
  earth.warps.edit:
    default: op
  # ECONOMY
  earth.economy.balance.others:
    default: op
  earth.economy.admin:
     default: op
  # GUNS
  earth.gun.give:
     default: op
   #CUSTOM ITEMS
  earth.ci.give:
     default: op